### ISSUE TITLE
Uneven edge

### ISSUE THREAD

**Issue by sapegin** [JamiLu/simply-blame#10]
Looks like the extension doesn't handle dates with 1 and 2 digits for the day and month correctly:

<img width="400" alt="image" src="https://github.com/JamiLu/simply-blame/assets/70067/78b3ccdc-8e6a-413f-812b-ea24cd7afc73">

**Comment by JamiLu** [comment]
@sapegin This should be resolved by the latest release 0.0.5 https://github.com/JamiLu/simply-blame/releases/tag/0.0.5
