### ISSUE TITLE
Parsing name failed

### ISSUE THREAD

**Issue by theod07** [JamiLu/simply-blame#11]
Blame failed to parse names:

I was taken here from the VSCode notification button. Let me know what information to share.
<img width="573" alt="image" src="https://github.com/user-attachments/assets/17100d2a-0ef5-4f97-ad66-6c7c9146dfdd">

**Comment by JamiLu** [comment]
Which version you have installed? If you haven't installed the latest version 0.0.4 then make sure that it is installed. If you enable the open raw blame in a text editor tab from the settings of the extension, and then compare what name actually didn't parse correctly. When you have got the letters that could not be parsed please post them here.

**Comment by JamiLu** [comment]
@theod07 Did you try to newest version and if did try, did it resolve the issue?

**Comment by xverges** [comment]
I just installed the extension for the first time (0.0.4) and I am getting this error also.

**Comment by JamiLu** [comment]
You could try to check via the git blame command or by opening the raw blame tab which name failed to parse or did the parsing of the whole file fail? 

You can enable the raw git blame in the simply-blame extension settings. When that is enabled then you can open the raw git blame on a new tab in the vs code from the context menu of the open file.

**Comment by JamiLu** [comment]
I will publish a new version tomorrow, that will introduce fixes to other issues of the extension but it will also introduce an improvement to bug reporting. The failed lines are then copied to your clipboard and you can then paste the failed lines here without checking the by yourself.

**Comment by JamiLu** [comment]
@theod07 @xverges I just made a new release 0.0.5 https://github.com/JamiLu/simply-blame/releases/tag/0.0.5 That has the improved report a bug functionality. So you can try that out. It will copy the failed lines that you can paste here on the bug report so that I could take a look what names actually fail to parse.

**Comment by JamiLu** [comment]
This could also be the issue of the file not being indexed in the git in cases such as the file is a new file or the file was renamed.
