### ISSUE TITLE
Fails on files that include dashes

### ISSUE THREAD

**Issue by xverges** [JamiLu/simply-blame#12]
Running on a file named ` /Users/xavier/src/dpm-scripts/dpm-utils.py` the extension tries to execute this command:

```
Command failed: cd /Users/xavier/src/dpm-scripts/dpm- && git blame utils.py /bin/sh: line 0: cd: /Users/xavier/src/dpm-scripts/dpm-: No such file or directory
```

**Comment by JamiLu** [comment]
Thanks for reporting this.

**Comment by JamiLu** [comment]
This should be fixed in the release 0.0.5 https://github.com/JamiLu/simply-blame/releases/tag/0.0.5, you could try it out.

**Comment by JamiLu** [comment]
This issue is resolved by the release. Closing the issue.

**Comment by JamiLu** [comment]
@gaevoy This release should fix the issue. https://github.com/JamiLu/simply-blame/releases/tag/1.10.2
If it does you can hit the star if you'd like :)
