### ISSUE TITLE
stdout maxBuffer length exceeded for large files

### ISSUE THREAD

**Issue by xverges** [JamiLu/simply-blame#13]
I see this error when trying on a large file

**Comment by JamiLu** [comment]
Thanks for reporting this issue. Have to take a look at this too.

**Comment by JamiLu** [comment]
This perhaps is resolved in the 0.0.5 release https://github.com/JamiLu/simply-blame/releases/tag/0.0.5,  you could try it out.

**Comment by JamiLu** [comment]
@xverges I close this issue as this might be resolved in the release. If the problem continues to occur please open a new ticket.
