### ISSUE TITLE
last line is not annotated

### ISSUE THREAD

**Issue by NanaGlutamate** [JamiLu/simply-blame#15]
if last line is not empty line, it looks wierd

**Comment by JamiLu** [comment]
Maybe if you could attach a screenshot here, please :)

**Comment by NanaGlutamate** [comment]
<img width="329" alt="image" src="https://github.com/user-attachments/assets/4afcce35-0147-4742-98e4-ca19bb8179ce">
thanks for your efforts

**Comment by JamiLu** [comment]
The issue is now fixed in the release 0.0.6 https://github.com/JamiLu/simply-blame/releases/tag/0.0.6
