### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by Jun10ng** [JamiLu/simply-blame#19]
Hi master, I very like your ext. May i raise two enhancements?
1. blamer name length with not-equal length, that looks wired.
2. date setting. my project is a very old project, I hope i can see a long early date code blame.
![image](https://github.com/user-attachments/assets/76b361f4-ce7d-498f-86a3-53feb50ef194)

**Comment by JamiLu** [comment]
@Jun10ng Thanks for reporting these issues. What do you mean by long early date? Do you mean a longer date format or something else? I need to take a look at the first issue. I assume the name is not Latin characters?

**Comment by Jun10ng** [comment]
> @Jun10ng Thanks for reporting these issues. What do you mean by long early date? Do you mean a longer date format or something else? I need to take a look at the first issue. I assume the name is not of Latin characters?

Sorry for the replay later. 
#1 I mean it would be better if simply blame can support for earlier date, such as five or six year ago.
#2 the all names are Latin characters. See below.
<img width="407" alt="image" src="https://github.com/user-attachments/assets/c23fc312-b1da-4de9-aac1-6e2625bfb58b">

**Comment by Jun10ng** [comment]
In GitLen, it has one configuration:
`"gitlens.blame.format": "${date} ${author|7-}" `.
able user to config how to show blame info.

**Comment by JamiLu** [comment]
> blamer name length with not-equal length, that looks wired.

This is a font family issue. You are using a font which the characters of the font are not of equal length. The most optimal solution would be a font agnostic but as for now the best thing is to use a font which characters are of equal length. For example the characters of these fonts are equal of length `'Droid Sans Mono', 'monospace', monospace`.

> I mean it would be better if simply blame can support for earlier date, such as five or six year ago.

Right. The point of the blame annotations is to show who and when did the recent or the latest changes on particular lines of code. This would be a separate bigger feature that would enable showing the history of the file in a sense that earlier changes could be inspected somehow.

**Comment by JamiLu** [comment]
@Jun10ng The latest release https://github.com/JamiLu/simply-blame/releases/tag/0.0.9 should fix the uneven edge for nonsymmetric fonts

**Comment by JamiLu** [comment]
I close this issue as the uneven edge is resolved
