### ISSUE TITLE
Command failed

### ISSUE THREAD

**Issue by crytt** [JamiLu/simply-blame#20]
> Command failed: cd && git blame c:\src\app\webapp\src\pages\Page\components\Page.tsx fatal: not a git repository (or any of the parent directories): .git

It used to work, but now something broke in the recent update(s).

**Comment by JamiLu** [comment]
@crytt  Thanks for reporting this issue. Sorry to hear that. I know what is the problem here. I have to fix this asap. But mean while please use the version. 0.0.4

**Comment by JamiLu** [comment]
You can install the previous version from from the extensions list by clicking the sprocket wheel icon and choosing the install another version then selecting the desired version.

**Comment by JamiLu** [comment]
@crytt This should be now fixed in the https://github.com/JamiLu/simply-blame/releases/tag/0.0.8

**Comment by crytt** [comment]
Works like a charm. Cheers!
