### ISSUE TITLE
Default colors are unreadable with light theme

### ISSUE THREAD

**Issue by sapegin** [JamiLu/simply-blame#9]
<img width="512" alt="image" src="https://github.com/JamiLu/simply-blame/assets/70067/d6d89b7e-6b51-491a-8d73-877d603ebd21">

**Comment by JamiLu** [comment]
I'll publish a new version of the extension tomorrow. The uneven edge and the light theme colors plus the revised dark theme colors are then included.

**Comment by JamiLu** [comment]
@xverges @sapegin The colors are now revised and the light theme is supported by the release 0.0.5 https://github.com/JamiLu/simply-blame/releases/tag/0.0.5
